// Generated by CoffeeScript 1.4.0
(function() {
  var rdfstore, request, url,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  request = require('request');

  url = require('url');

  rdfstore = require('rdfstore');

  WebID.VerificationAgent = (function() {

    function VerificationAgent(certificate) {
      this.verifyWebID = __bind(this.verifyWebID, this);

      var _this = this;
      this.uris = [];
      this.subjectAltName = certificate.subjectaltname;
      this.modulus = certificate.modulus;
      this.exponent = parseInt(certificate.exponent, 16).toString();
      this.subjectAltName.replace(/URI:([^, ]+)/g, function(match, uri) {
        return _this.uris.push(uri);
      });
    }

    VerificationAgent.prototype.verify = function(success, error, _arg) {
      var uri, _ref;
      _arg;
      if ((_ref = this.waitFor) == null) {
        this.waitFor = 0;
      }
      if (this.uris.length === 0) {
        return error('certificateProvidedSAN');
      } else {
        uri = this.uris.shift();
        return this.getWebID(uri, success, error);
      }
    };

    VerificationAgent.prototype.getWebID = function(uri, success, error) {
      var options, parsedURI, r,
        _this = this;
      parsedURI = url.parse(uri);
      options = {
        url: parsedURI,
        method: 'GET',
        headers: {
          Accept: 'text/turtle, application/ld+json'
        }
      };
      return r = request(options, function(err, res, body) {
        if (err) {
          return error('profileGet');
        } else {
          return _this.verifyWebID(uri, body, res.headers['content-type'], success, error);
        }
      });
    };

    VerificationAgent.prototype.verifyWebID = function(webID, profile, mimeType, successCB, errorCB) {
      var _this = this;
      return rdfstore.create(function(store) {
        return store.load(mimeType, profile, function(success, results) {
          if (success) {
	    debugger;
            return store.execute("PREFIX cert: <http://www.w3.org/ns/auth/cert#> SELECT ?webid ?m ?e WHERE { ?webid cert:key ?key . ?key cert:modulus ?m . ?key cert:exponent ?e . }", function(success, results) {
              var exponent, i, modulus;
              if (success) {
                i = 0;
                while (i < results.length) {
                  modulus = null;
                  exponent = null;
                  if (results[i].webid.value === webID) {
                    modulus = results[i].m.value;
                    exponent = results[i].e.value;
                    if ((modulus != null) && (exponent != null) && (modulus.toLowerCase() === _this.modulus.toLowerCase()) && (exponent === _this.exponent)) {
                      successCB(webID);
                      return void 0;
                    }
                  }
                  i++;
                }
                return errorCB("profileAllKeysWellFormed");
              } else {
                return errorCB("profileAllKeysWellFormed");
              }
            });
          } else {
            return errorCB("profileWellFormed");
          }
        });
      });
    };

    return VerificationAgent;

  })();

}).call(this);
